apiVersion: apps/v1
kind: Deployment
metadata:
  name: cinema-visitors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-visitors
  template:
    metadata:
      labels:
        app: cinema-visitors
    spec:
      containers:
        - image: myfirstmolly/visitorservice
          name: cinema-visitors
          ports:
            - containerPort: 8084
              name: cinema-visitors
          env:
            - name: POSTGRES_ENDPOINT
              value: "jdbc:postgresql://192.168.0.101:5432/"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_USERNAME
              value: "postgres"